const africa = document.querySelector(".africa");
const america = document.querySelector(".americas");
const asia = document.querySelector(".asia");
const europe = document.querySelector(".europe");
const oceania = document.querySelector(".oceania");
const btnBox = document.querySelector(".all-btn");
const allContinentBtn = document.querySelectorAll(".continent-btn");
const hiddenDivMessage = document.querySelector(".hidden-info");
hiddenDivMessage.style.visibility = "hidden";
